version: 2.1

orbs:
  architect: giantswarm/architect@5.15.0

workflows:
  build:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: cluster-api-cleaner-cloud-director
        resource_class: xlarge
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
          # Trigger the job also on git tag.
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        name: push-to-app-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: cluster-api-cleaner-cloud-director
        requires:
        - push-to-registries
        filters:
          # Trigger the job also on git tag.
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-collection:
        context: architect
        name: push-to-cloud-director-app-collection
        app_name: cluster-api-cleaner-cloud-director
        app_collection_repo: cloud-director-app-collection
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
